import { readFileSync, existsSync, readdirSync, statSync } from 'node:fs';
import path from 'node:path';

const root = process.cwd();
const requiredFiles = [
  'module.json',
  'package.json',
  'README.md',
  'CHANGELOG.md',
  'LICENSE',
  'src/main.js',
  'src/apps/LdHeroPointz.js',
  'src/apps/LogViewer.js',
  'styles/ld-hero-pointz.css',
  'styles/log-viewer.css',
  'templates/settings.html',
  'templates/log-viewer.hbs',
  'languages/en.json'
];

for (const relativePath of requiredFiles) {
  const fullPath = path.join(root, relativePath);
  if (!existsSync(fullPath)) {
    throw new Error(`Missing required file: ${relativePath}`);
  }
}

const moduleJson = JSON.parse(readFileSync(path.join(root, 'module.json'), 'utf8'));
const packageJson = JSON.parse(readFileSync(path.join(root, 'package.json'), 'utf8'));
const readme = readFileSync(path.join(root, 'README.md'), 'utf8');
const changelog = readFileSync(path.join(root, 'CHANGELOG.md'), 'utf8');
const locale = JSON.parse(readFileSync(path.join(root, 'languages/en.json'), 'utf8'));

if (moduleJson.version !== packageJson.version) {
  throw new Error(`Version mismatch: module.json=${moduleJson.version}, package.json=${packageJson.version}`);
}

if (!readme.includes(moduleJson.version)) {
  throw new Error(`README.md does not mention version ${moduleJson.version}`);
}

if (!changelog.includes(`## ${moduleJson.version}`)) {
  throw new Error(`CHANGELOG.md is missing heading ## ${moduleJson.version}`);
}

if (moduleJson.protected !== false) {
  throw new Error('Patreon-gated premium modules must use protected: false.');
}

if (moduleJson.compatibility?.minimum !== 13 || moduleJson.compatibility?.verified !== 14) {
  throw new Error('module.json compatibility must be numeric and pinned to Foundry 13 minimum and verified 14.');
}

if (moduleJson.id !== 'ld-hero-pointz') {
  throw new Error('module.json id must be ld-hero-pointz.');
}

const author = moduleJson.authors?.[0];
if (author?.name !== "Lisa's Dungeon") {
  throw new Error("module.json author name must be Lisa's Dungeon.");
}
if (author?.discord !== 'MystryssLysa') {
  throw new Error('module.json discord must be MystryssLysa.');
}
if (author?.email !== 'Lisasdungeon@gmail.com') {
  throw new Error('module.json email must be Lisasdungeon@gmail.com.');
}
if (author?.url !== 'https://github.com/lisasdungeon') {
  throw new Error('module.json author url must be https://github.com/lisasdungeon.');
}

if (!Array.isArray(moduleJson.styles) || moduleJson.styles.length === 0) {
  throw new Error('module.json must declare at least one stylesheet.');
}

if (!Array.isArray(moduleJson.languages) || moduleJson.languages.length === 0) {
  throw new Error('module.json must declare at least one language entry.');
}

if (moduleJson.socket !== true) {
  throw new Error('module.json socket must be true.');
}

if (locale['LDHEROEPOINTZ.GM.Header']?.includes('Reserves')) {
  throw new Error('languages/en.json still uses Reserves in the GM header.');
}

const emDash = /\u2014|\u2013/;
for (const relativePath of ['README.md', 'CHANGELOG.md']) {
  const content = readFileSync(path.join(root, relativePath), 'utf8');
  if (emDash.test(content)) {
    throw new Error(`${relativePath} contains an em dash or en dash.`);
  }
}

const blocked = [
  /\bChatGPT\b/i,
  /\bOpenAI\b/i,
  /\bClaude\b/,
  /\bCopilot\b/i,
  /\bGrok\b/,
  /\bAI assistance\b/i,
  /\bgenerated by\b/i
];
for (const relativePath of ['README.md', 'CHANGELOG.md', 'LICENSE']) {
  const content = readFileSync(path.join(root, relativePath), 'utf8');
  for (const pattern of blocked) {
    if (pattern.test(content)) {
      throw new Error(`${relativePath} contains blocked term matching ${pattern}`);
    }
  }
}

function walkJs(dir, files = []) {
  for (const entry of readdirSync(dir)) {
    const full = path.join(dir, entry);
    const st = statSync(full);
    if (st.isDirectory()) walkJs(full, files);
    else if (entry.endsWith('.js')) files.push(full);
  }
  return files;
}

const srcFiles = walkJs(path.join(root, 'src'));
for (const file of srcFiles) {
  const lines = readFileSync(file, 'utf8').split(/\r?\n/).length;
  if (lines > 500) {
    throw new Error(`${path.relative(root, file)} has ${lines} lines (cap is 500).`);
  }
}

console.log('ld-hero-pointz validation passed');
